language: python
python:
- '2.7'
- '2.6'

env:
  global:
  - secure: TVFg6VDgzyE8VjPQVepE2JTXNbjpCBiiB3tF+rtjwzinnyPaesJ/a1P4XazzdP98Yjx1BPUxvB5kR0uDhseoUOGnZ0F5oeAr44sXZ1itGyANmFsF+cTK/zU2Ov7j+8deDypBxvgOad/LzAE0wihgNFpFopCPs0OdaBn7pfBiv40=
  - secure: dAgkutD1GS4VhlRF6tmC0MoKUTakIaFcaQ8vKBQzW9Z5Q+Knjmuwx4iArc73kByg5T1KloERNcKoAGrya9rwuUYFMldLtqeYK/nTMx8ejRZ0PmGqlpmtGvJR8iN+FSdLuiVkfKvZewRHybgQt0mL2886tihf1dbVWDWTcIk/gSc=


install: pip install -r requirements.txt
script: python run_tests.py
