language: python

python:
    - '2.6'
    - '2.7'
    - '3.3'
    - '3.4'
    - 'pypy'

env:
    - DJANGO="django>=1.4,<1.5"
    - DJANGO="django>=1.5,<1.6"
    - DJANGO="django>=1.6,<1.7"

install:
    - pip install --use-mirrors ${DJANGO}
    - pip install --use-mirrors -r requirements.txt
    - pip install --use-mirrors -r test_requirements.txt

script:
    - python manage.py test

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="django>=1.4,<1.5"
